### ISSUE TITLE
campaign page should show sending date window

### ISSUE THREAD

**Issue by jjb** [vote-forward/votefwd#339]
Hi Scott! We emailed a bit in the midterms.

I think maybe pages like this: https://votefwd.org/dashboard/PASD37

Should show the letter mailing window on them. WDYT?

**Comment by sjforman** [comment]
Hey John, thanks for this, totally agree! I've started adding the date to the description, but that's a bit of a kludge and is not that legible. Would be better to make it structured and highlighted. 

The good news: would be fairly straightforward in that we store the election date in the database as `districts.election_date`. 

The bad news: that field is a bit overloaded semantically, since we also now have two types of campaigns — "registration" campaigns, and "gotv" campaigns. 

For "registration" ("vrbm") campaigns, `election_date` currently denotes "the deadline to mail the letters," whereas for "gotv" campaigns it means "subtract seven days from this date to get the precise date on which letters should be sent."

"Type" is also recorded in the database as `districts.type`. So we'd have to check this field and put in an if statement to control what's rendered re: dates. Not a big deal, I just haven't gotten a chance to do it yet. But if you'd like to give it a go, pull request would be welcome!

**Comment by sjforman** [comment]
This was done via #365.

**Comment by jjb** [comment]
🆒
